### ISSUE TITLE
Crash on start with 1.20.1

### ISSUE THREAD

**Issue by A5ho9999** [SchmarrnDevs/Lighty#27]
Fabric 1.20.1
Lighty Version: https://modrinth.com/mod/lighty/version/2.0.3+1.20.1

```
java.lang.RuntimeException: Could not execute entrypoint stage 'client' due to errors, provided by 'lighty'!
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke0$0(EntrypointUtils.java:51)
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:49)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35)
	at net.fabricmc.loader.impl.game.minecraft.Hooks.startClient(Hooks.java:53)
	at net.minecraft.class_310.<init>(class_310.java:458)
	at net.minecraft.client.main.Main.main(Main.java:211)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: java.lang.NullPointerException: Cannot invoke "net.minecraft.class_1060.method_34590(net.minecraft.class_2960, net.minecraft.class_1044)" because "textureManager" is null
	at eu.midnightdust.visualoverhaul.IconicButtons.init(IconicButtons.java:47)
	at eu.midnightdust.visualoverhaul.IconicButtons.<init>(IconicButtons.java:27)
	at net.minecraft.class_4264.handler$imk000$visualoverhaul$iconic$onInitButton(class_4264.java:522)
	at net.minecraft.class_4264.<init>(class_4264.java:21)
	at net.minecraft.class_4185.<init>(class_4185.java:86)
	at net.minecraft.class_4185$class_7840.method_46431(class_4185.java:72)
	at dev.schmarrn.lighty.ui.ModeSwitcherScreen.addButton(ModeSwitcherScreen.java:57)
	at dev.schmarrn.lighty.api.ModeManager.registerMode(ModeManager.java:26)
	at dev.schmarrn.lighty.mode.CarpetMode.init(CarpetMode.java:140)
	at dev.schmarrn.lighty.Lighty.init(Lighty.java:23)
	at dev.schmarrn.lighty.fabric.LightyFabric.onInitializeClient(LightyFabric.java:36)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47)
	... 7 more
```
Crash Log
https://gist.github.com/A5ho9999/10ffc461adc0245d7b235bac5e4b6c09

**Comment by andi-makes** [comment]
Thank you for reporting this issue! 

It seems like this is a mod incompatibility with one of the other mods you have installed. To verify this, can you try launching Minecraft with just Lighty and FabricAPI? If the game launches just fine with just those two mods, it is a compatibility issue with another mod.

If it is a compatibility issue with another mod, can you try and narrow it down to the minimal required mods for reproducing this issue? 

Please provide a crash log with only the minimal required mods enabled.

Thanks!

**Comment by andi-makes** [comment]
I think I fixed it (with the help of agnor99), will release a new lighty version later today

**Comment by andi-makes** [comment]
https://modrinth.com/mod/lighty/version/v2.0.4+1.20.1

This version should fix it, feel free to re-open this issue if the same crash still exitst

**Comment by A5ho9999** [comment]
Thanks will check lately today, sorry didn't get around to checking compatibility

**Comment by A5ho9999** [comment]
Yup that did the trick, thanks!
